import { useSession, signOut } from 'next-auth/react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Link from 'next/link';

const Contact = () => {
  const router = useRouter();

  const { status, data: session } = useSession({
    required: true,
    onUnauthenticated() {
      router.replace('/api/auth/signin');
    },
  }) as any;

  if (status === 'loading') {
    return <h1>Loading...</h1>;
  }

  return (
    <>
      <Head>
        <title>Custom Next-Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto flex flex-col gap-4 items-center">
        <h1 className=" text-4xl text-black">Welcome to the Contact us page {session.user?.name}</h1>
        <br />
        <img src={session.user.image} alt="" height={200} width={200} />
        <Link href={'/'}>Back</Link>
        <button
          onClick={() => signOut()}
          className="bg-red-500 capitalize w-40 text-white font-semibold p-2 rounded-md"
        >
          Sign out
        </button>
      </div>
    </>
  );
};

export default Contact;
